spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms
    username: root
    password: Pirate@1601
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG